import { ModelConfig } from './types';

export const MODEL_CATALOG: ModelConfig[] = [
  // === FREE TIER ===
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'openrouter',
    modelName: 'deepseek/deepseek-chat',
    type: 'FREE',
    description: 'High-performance open-weight model by DeepSeek.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    fallbackModelId: 'deepseek-ai/DeepSeek-V3',
    freeTier: true,
  },
  {
    id: 'qwen-2.5-72b',
    name: 'Qwen 2.5 (72B)',
    provider: 'openrouter',
    modelName: 'qwen/qwen-2.5-72b-instruct',
    type: 'FREE',
    description: 'Alibaba\'s large open-weight model, strong at reasoning.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    fallbackModelId: 'Qwen/Qwen2.5-72B-Instruct',
    freeTier: true,
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 (8B)',
    provider: 'openrouter',
    modelName: 'meta-llama/llama-3.1-8b-instruct',
    type: 'FREE',
    description: 'Meta\'s efficient open-source instruct model.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    fallbackModelId: 'meta-llama/Llama-3.1-8B-Instruct',
    freeTier: true,
  },
  {
    id: 'mistral-7b',
    name: 'Mistral 7B',
    provider: 'openrouter',
    modelName: 'mistralai/mistral-7b-instruct',
    type: 'FREE',
    description: 'Fast and capable open model by Mistral AI.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    fallbackModelId: 'mistralai/Mistral-7B-Instruct-v0.3',
    freeTier: true,
  },

  // === FRONTIER TIER ===
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openrouter',
    modelName: 'openai/gpt-4o',
    type: 'FRONTIER',
    description: 'OpenAI\'s flagship multimodal frontier model.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    freeTier: false,
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'openrouter',
    modelName: 'anthropic/claude-3.5-sonnet',
    type: 'FRONTIER',
    description: 'Anthropic\'s balanced frontier model, strong safety alignment.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    freeTier: false,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'openrouter',
    modelName: 'google/gemini-2.5-flash:free',
    type: 'FRONTIER',
    description: 'Google\'s most capable frontier reasoning model.',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    freeTier: false,
  },
];
